In [61]:
import pandas as pd
import numpy as np

In [62]:
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()

In [63]:
df = pd.read_csv("Sample Apple vs. Orange.csv")

In [64]:
df

,Fruit Type,Bumpy Skin,Thickness of Skin (mm),Where it was grown (in US),Owner's Name
0,Apple,No,0.2,North,Alice
1,Apple,No,0.4,North,Alice
2,Apple,No,0.3,South,Alice
3,Apple,Yes,0.2,North,Alice
4,Apple,No,0.3,North,Alice
5,Orange,Yes,0.8,South,Bob
6,Orange,Yes,0.8,South,Bob
7,Orange,Yes,0.6,South,Bob
8,Orange,No,0.9,North,Bob
9,Orange,Yes,1.0,North,Bob
10,Apple,No,0.6,North,Alice
11,Apple,No,0.3,North,Alice
12,Apple,Yes,0.4,North,Alice
13,Orange,Yes,0.8,South,Bob
14,Orange,Yes,0.6,South,Bob
15,Orange,Yes,0.9,South,Bob
16,Orange,Yes,0.8,South,Bob
17,Apple,No,0.3,North,Alice
18,Apple,No,0.3,North,Alice

In [65]:
processed_df = pd.DataFrame()

In [66]:
for label, _ in df.items():
    if (label == "Thickness of Skin (mm)"):
        continue
    processed_df[label] = LE.fit_transform(df[label])
processed_df['Thickness of Skin (mm)'] = df['Thickness of Skin (mm)']

In [67]:
processed_df = processed_df.sample(frac=1)
processed_df

,Fruit Type,Bumpy Skin,Where it was grown (in US),Owner's Name,Thickness of Skin (mm)
11,0,0,0,0,0.3
8,1,0,0,1,0.9
15,1,1,1,1,0.9
10,0,0,0,0,0.6
13,1,1,1,1,0.8
17,0,0,0,0,0.3
12,0,1,0,0,0.4
4,0,0,0,0,0.3
1,0,0,0,0,0.4
5,1,1,1,1,0.8
2,0,0,1,0,0.3
16,1,1,1,1,0.8
7,1,1,1,1,0.6
9,1,1,0,1,1.0
14,1,1,1,1,0.6
6,1,1,1,1,0.8
3,0,1,0,0,0.2
0,0,0,0,0,0.2
18,0,0,0,0,0.3

In [68]:
X = processed_df.drop("Fruit Type", axis=1)
y = processed_df['Fruit Type']
# 1 = orange

In [98]:
c_coef = 50

In [99]:
clf = SVC(gamma='auto', kernel='linear', C=c_coef)

In [100]:
clf.fit(X, y)

SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [101]:
clf.coef_

array([[0.07920892, 0.07920892, 1.84140271, 0.52865814]])

In [102]:
clf_without_hair = SVC(gamma='auto', kernel='linear', C=c_coef)
clf_without_hair.fit(X.drop("Owner's Name", axis=1), y)

SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [103]:
clf_without_hair.coef_

array([[0.99992021, 0.99992021, 6.66613626]])

In [104]:
with_hair = np.around(clf.coef_, decimals=3)
without_hair = np.around(clf_without_hair.coef_, decimals=3)

In [105]:
print("With Hair Variable | Without Hair Variable")
print(f"Weight of Skin Bumpiness:\t{with_hair[0][0]} | {without_hair[0][0]}")
print(f"Weight of Location Grown:\t{with_hair[0][1]} | {without_hair[0][1]}")
print(f"Weight of Owner's Name:\t\t{with_hair[0][2]}")
print(f"Weight of Thickness of Skin:\t{with_hair[0][3]} | {without_hair[0][2]}")

With Hair Variable | Without Hair Variable
Weight of Skin Bumpiness:	0.079 | 1.0
Weight of Location Grown:	0.079 | 1.0
Weight of Owner's Name:		1.841
Weight of Thickness of Skin:	0.529 | 6.666